'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace FDAServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FDAServiceReference.WS_LICENSE_SEARCHSoap")>  _
    Public Interface WS_LICENSE_SEARCHSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_FOOD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_FOOD(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_FOOD", ReplyAction:="*")>  _
        Function GET_DATA_FOODAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_FOOD_FULL", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_FOOD_FULL(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_FOOD_FULL", ReplyAction:="*")>  _
        Function GET_DATA_FOOD_FULLAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DRUG_LCN_INFORMATION", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DRUG_LCN_INFORMATION(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DRUG_LCN_INFORMATION", ReplyAction:="*")>  _
        Function GET_DRUG_LCN_INFORMATIONAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DRUG_INFORMATION", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DRUG_INFORMATION(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DRUG_INFORMATION", ReplyAction:="*")>  _
        Function GET_DRUG_INFORMATIONAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_CMT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_CMT(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_CMT", ReplyAction:="*")>  _
        Function GET_DATA_CMTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_DRUG", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_DRUG(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_DRUG", ReplyAction:="*")>  _
        Function GET_DATA_DRUGAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_HERB", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_HERB(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_HERB", ReplyAction:="*")>  _
        Function GET_DATA_HERBAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_NCT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_NCT(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_NCT", ReplyAction:="*")>  _
        Function GET_DATA_NCTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_MDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_MDC(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_MDC", ReplyAction:="*")>  _
        Function GET_DATA_MDCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_TXC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_TXC(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_TXC", ReplyAction:="*")>  _
        Function GET_DATA_TXCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_ALL", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_ALL(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_ALL", ReplyAction:="*")>  _
        Function GET_DATA_ALLAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_ALL_LCN", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_ALL_LCN(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_ALL_LCN", ReplyAction:="*")>  _
        Function GET_DATA_ALL_LCNAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_DRUG", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_DRUG(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_DRUG", ReplyAction:="*")>  _
        Function GET_DATA_LCN_DRUGAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_FOOD", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_FOOD(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_FOOD", ReplyAction:="*")>  _
        Function GET_DATA_LCN_FOODAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_NCT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_NCT(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_NCT", ReplyAction:="*")>  _
        Function GET_DATA_LCN_NCTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_NCT_STATUS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_NCT_STATUS(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_NCT_STATUS", ReplyAction:="*")>  _
        Function GET_DATA_LCN_NCT_STATUSAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_TXC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_TXC(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_TXC", ReplyAction:="*")>  _
        Function GET_DATA_LCN_TXCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_CMT", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_CMT(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_CMT", ReplyAction:="*")>  _
        Function GET_DATA_LCN_CMTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_MDC", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GET_DATA_LCN_MDC(ByVal DATAS As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GET_DATA_LCN_MDC", ReplyAction:="*")>  _
        Function GET_DATA_LCN_MDCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_LICENSE_SEARCHSoapChannel
        Inherits FDAServiceReference.WS_LICENSE_SEARCHSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_LICENSE_SEARCHSoapClient
        Inherits System.ServiceModel.ClientBase(Of FDAServiceReference.WS_LICENSE_SEARCHSoap)
        Implements FDAServiceReference.WS_LICENSE_SEARCHSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GET_DATA_FOOD(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_FOOD
            Return MyBase.Channel.GET_DATA_FOOD(DATAS)
        End Function
        
        Public Function GET_DATA_FOODAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_FOODAsync
            Return MyBase.Channel.GET_DATA_FOODAsync(DATAS)
        End Function
        
        Public Function GET_DATA_FOOD_FULL(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_FOOD_FULL
            Return MyBase.Channel.GET_DATA_FOOD_FULL(DATAS)
        End Function
        
        Public Function GET_DATA_FOOD_FULLAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_FOOD_FULLAsync
            Return MyBase.Channel.GET_DATA_FOOD_FULLAsync(DATAS)
        End Function
        
        Public Function GET_DRUG_LCN_INFORMATION(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DRUG_LCN_INFORMATION
            Return MyBase.Channel.GET_DRUG_LCN_INFORMATION(DATAS)
        End Function
        
        Public Function GET_DRUG_LCN_INFORMATIONAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DRUG_LCN_INFORMATIONAsync
            Return MyBase.Channel.GET_DRUG_LCN_INFORMATIONAsync(DATAS)
        End Function
        
        Public Function GET_DRUG_INFORMATION(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DRUG_INFORMATION
            Return MyBase.Channel.GET_DRUG_INFORMATION(DATAS)
        End Function
        
        Public Function GET_DRUG_INFORMATIONAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DRUG_INFORMATIONAsync
            Return MyBase.Channel.GET_DRUG_INFORMATIONAsync(DATAS)
        End Function
        
        Public Function GET_DATA_CMT(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_CMT
            Return MyBase.Channel.GET_DATA_CMT(DATAS)
        End Function
        
        Public Function GET_DATA_CMTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_CMTAsync
            Return MyBase.Channel.GET_DATA_CMTAsync(DATAS)
        End Function
        
        Public Function GET_DATA_DRUG(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_DRUG
            Return MyBase.Channel.GET_DATA_DRUG(DATAS)
        End Function
        
        Public Function GET_DATA_DRUGAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_DRUGAsync
            Return MyBase.Channel.GET_DATA_DRUGAsync(DATAS)
        End Function
        
        Public Function GET_DATA_HERB(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_HERB
            Return MyBase.Channel.GET_DATA_HERB(DATAS)
        End Function
        
        Public Function GET_DATA_HERBAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_HERBAsync
            Return MyBase.Channel.GET_DATA_HERBAsync(DATAS)
        End Function
        
        Public Function GET_DATA_NCT(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_NCT
            Return MyBase.Channel.GET_DATA_NCT(DATAS)
        End Function
        
        Public Function GET_DATA_NCTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_NCTAsync
            Return MyBase.Channel.GET_DATA_NCTAsync(DATAS)
        End Function
        
        Public Function GET_DATA_MDC(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_MDC
            Return MyBase.Channel.GET_DATA_MDC(DATAS)
        End Function
        
        Public Function GET_DATA_MDCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_MDCAsync
            Return MyBase.Channel.GET_DATA_MDCAsync(DATAS)
        End Function
        
        Public Function GET_DATA_TXC(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_TXC
            Return MyBase.Channel.GET_DATA_TXC(DATAS)
        End Function
        
        Public Function GET_DATA_TXCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_TXCAsync
            Return MyBase.Channel.GET_DATA_TXCAsync(DATAS)
        End Function
        
        Public Function GET_DATA_ALL(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_ALL
            Return MyBase.Channel.GET_DATA_ALL(DATAS)
        End Function
        
        Public Function GET_DATA_ALLAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_ALLAsync
            Return MyBase.Channel.GET_DATA_ALLAsync(DATAS)
        End Function
        
        Public Function GET_DATA_ALL_LCN(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_ALL_LCN
            Return MyBase.Channel.GET_DATA_ALL_LCN(DATAS)
        End Function
        
        Public Function GET_DATA_ALL_LCNAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_ALL_LCNAsync
            Return MyBase.Channel.GET_DATA_ALL_LCNAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_DRUG(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_DRUG
            Return MyBase.Channel.GET_DATA_LCN_DRUG(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_DRUGAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_DRUGAsync
            Return MyBase.Channel.GET_DATA_LCN_DRUGAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_FOOD(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_FOOD
            Return MyBase.Channel.GET_DATA_LCN_FOOD(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_FOODAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_FOODAsync
            Return MyBase.Channel.GET_DATA_LCN_FOODAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_NCT(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_NCT
            Return MyBase.Channel.GET_DATA_LCN_NCT(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_NCTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_NCTAsync
            Return MyBase.Channel.GET_DATA_LCN_NCTAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_NCT_STATUS(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_NCT_STATUS
            Return MyBase.Channel.GET_DATA_LCN_NCT_STATUS(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_NCT_STATUSAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_NCT_STATUSAsync
            Return MyBase.Channel.GET_DATA_LCN_NCT_STATUSAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_TXC(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_TXC
            Return MyBase.Channel.GET_DATA_LCN_TXC(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_TXCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_TXCAsync
            Return MyBase.Channel.GET_DATA_LCN_TXCAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_CMT(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_CMT
            Return MyBase.Channel.GET_DATA_LCN_CMT(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_CMTAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_CMTAsync
            Return MyBase.Channel.GET_DATA_LCN_CMTAsync(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_MDC(ByVal DATAS As String) As System.Data.DataSet Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_MDC
            Return MyBase.Channel.GET_DATA_LCN_MDC(DATAS)
        End Function
        
        Public Function GET_DATA_LCN_MDCAsync(ByVal DATAS As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements FDAServiceReference.WS_LICENSE_SEARCHSoap.GET_DATA_LCN_MDCAsync
            Return MyBase.Channel.GET_DATA_LCN_MDCAsync(DATAS)
        End Function
    End Class
End Namespace
