'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GPP

    '''<summary>
    '''hdLocationUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLocationUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdRequestUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdRequestUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdGPPUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdGPPUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelGPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGPP As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q8 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q9 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumScoreS1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS2Q1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumScoreS2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumScoreS3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumScoreS4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q8 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q9 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q10 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q10 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q11 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q11 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q12 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q12 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumScoreS5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTotalScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFinalScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFinalScore As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFinalPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalPercent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFinalResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFinalResult As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTopic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdAccID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAccID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmdUpImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpImg As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdImg As Global.System.Web.UI.WebControls.GridView
End Class
